import React, { useState } from 'react';
import { Contract, ContractObligation, ActionItem } from '../types';
import {
  Sparkles,
  X,
  FileText,
  Printer,
  Copy,
  Check,
  Calendar,
  AlertTriangle,
  ShieldCheck,
  Building2,
  DollarSign
} from 'lucide-react';

interface ExecutiveSummaryModalProps {
  isOpen: boolean;
  onClose: () => void;
  contract: Contract;
  obligations: ContractObligation[];
  actionItems: ActionItem[];
  onOpenClause?: (page: number, sectionRef: string) => void;
}

export const ExecutiveSummaryModal: React.FC<ExecutiveSummaryModalProps> = ({
  isOpen,
  onClose,
  contract,
  obligations,
  actionItems,
  onOpenClause,
}) => {
  const [copied, setCopied] = useState(false);

  if (!isOpen) return null;

  const handleCopySummary = () => {
    const text = `EXECUTIVE SUMMARY: ${contract.title}
Parties: ${contract.parties.client} and ${contract.parties.vendor}
Term: ${contract.effectiveDate} to ${contract.expirationDate}
Payment Terms: Net 30 days (Flagged: conflicting Section 9.2 mentions Net 45)
Renewal Terms: Automatic 12-month renewal unless 30 days written notice served by Oct 15, 2026.

CRITICAL ACTIONS & DEADLINES:
1. Oct 15, 2026 - Non-Renewal Notice (Section 8.2) - URGENT
2. Oct 05, 2026 - Monthly SLA & Compliance Report (Section 7.3)
3. Oct 30, 2026 - Quarterly License Fee $42,500 (Section 4.1)

FLAGGED RISKS & INCONSISTENCIES:
- Payment terms conflict: Section 4.1 specifies Net 30, whereas Section 9.2 specifies Net 45. Reconciliation required prior to invoice processing.
- Vendor liability cap: Capped at 12 months fees under Section 12.1.

Generated by ContractLens AI Agent.`;

    navigator.clipboard.writeText(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="fixed inset-0 z-50 bg-black/85 backdrop-blur-md flex items-center justify-center p-4 animate-in fade-in duration-200">
      <div className="bg-[#0B0E1D] border border-violet-500/40 rounded-2xl max-w-2xl w-full p-6 shadow-[0_20px_60px_rgba(0,0,0,0.95)] glow-subtle-brand space-y-5">
        {/* Header */}
        <div className="flex items-start justify-between gap-4 border-b border-violet-950/80 pb-4">
          <div className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl bg-gradient-to-r from-violet-600 via-indigo-600 to-cyan-500 flex items-center justify-center text-white shadow-[0_0_14px_rgba(6,182,212,0.5)]">
              <Sparkles className="w-5 h-5" />
            </div>
            <div>
              <span className="text-[10px] font-bold text-cyan-400 uppercase tracking-widest font-mono-code block">
                AI EXECUTIVE BRIEFING
              </span>
              <h3 className="text-xl font-extrabold text-white tracking-tight">
                Executive Brief: {contract.title}
              </h3>
            </div>
          </div>

          <div className="flex items-center gap-2">
            <button
              onClick={handleCopySummary}
              className="p-1.5 text-slate-400 hover:text-cyan-300 rounded-lg hover:bg-[#141A33] transition-colors flex items-center gap-1 text-xs font-semibold"
              title="Copy executive summary"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
              <span className="hidden sm:inline">{copied ? 'Copied' : 'Copy'}</span>
            </button>
            <button
              onClick={onClose}
              className="text-slate-400 hover:text-white p-1 rounded-lg hover:bg-[#151B38] transition-colors"
            >
              <X className="w-5 h-5" />
            </button>
          </div>
        </div>

        {/* Content Body */}
        <div className="space-y-4 text-sm max-h-[60vh] overflow-y-auto pr-1 no-scrollbar">
          {/* Executive Overview */}
          <div className="p-4 rounded-xl bg-[#0E1326]/80 border border-violet-950/70 space-y-2">
            <span className="text-[10px] font-bold uppercase tracking-wider text-cyan-400 font-mono-code flex items-center gap-1.5">
              <Building2 className="w-3.5 h-3.5" />
              <span>CONTRACT OVERVIEW & SCOPE</span>
            </span>
            <p className="text-slate-200 leading-relaxed text-xs sm:text-sm">
              This master agreement establishes recurring cloud enterprise software provisioning between <strong>{contract.parties.client}</strong> (Client) and <strong>{contract.parties.vendor}</strong> (Vendor). Operating under Delaware state law, the active term spans <strong>{contract.effectiveDate}</strong> through <strong>{contract.expirationDate}</strong> with auto-renewal covenants.
            </p>
          </div>

          {/* Key Commercial Terms Grid */}
          <div className="grid grid-cols-1 sm:grid-cols-2 gap-3">
            <div className="p-3.5 rounded-xl bg-[#090C1A] border border-violet-950/60">
              <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 font-mono-code flex items-center gap-1">
                <DollarSign className="w-3 h-3 text-cyan-400" />
                <span>COMMERCIAL & PAYMENT</span>
              </span>
              <p className="text-sm font-semibold text-white mt-1">
                {contract.summary.payment}
              </p>
              <span className="text-[11px] text-amber-400 font-mono-code block mt-0.5">
                Note: Section 9.2 conflicting Net 45
              </span>
            </div>

            <div className="p-3.5 rounded-xl bg-[#090C1A] border border-violet-950/60">
              <span className="text-[10px] font-bold uppercase tracking-wider text-slate-400 font-mono-code flex items-center gap-1">
                <Calendar className="w-3 h-3 text-violet-400" />
                <span>RENEWAL & NOTICE</span>
              </span>
              <p className="text-sm font-semibold text-white mt-1">
                30 Days Written Notice
              </p>
              <span className="text-[11px] text-rose-400 font-mono-code block mt-0.5">
                Cutoff: October 15, 2026 (18 days)
              </span>
            </div>
          </div>

          {/* Critical Actions & Deadlines */}
          <div className="p-4 rounded-xl bg-[#090C1A] border border-violet-950/60 space-y-2.5">
            <span className="text-[10px] font-bold uppercase tracking-wider text-amber-400 font-mono-code flex items-center gap-1.5">
              <Calendar className="w-3.5 h-3.5" />
              <span>IMMEDIATE ACTIONS & CRITICAL DATES</span>
            </span>

            <div className="divide-y divide-violet-950/50 space-y-2">
              <div className="pt-2 first:pt-0 flex items-start justify-between gap-3 text-xs">
                <div>
                  <strong className="text-white">Notice of Non-Renewal or Extension</strong>
                  <p className="text-slate-400">Must be delivered in writing before 5:00 PM EST on Oct 15, 2026 to prevent automatic 12-month lock-in.</p>
                </div>
                <span className="font-mono-code font-bold text-rose-400 bg-rose-950/50 px-2 py-0.5 rounded whitespace-nowrap">
                  Oct 15, 2026
                </span>
              </div>

              <div className="pt-2 flex items-start justify-between gap-3 text-xs">
                <div>
                  <strong className="text-white">Quarterly Maintenance Fee ($42,500)</strong>
                  <p className="text-slate-400">Recurring license disbursement subject to Net 30 terms.</p>
                </div>
                <span className="font-mono-code font-bold text-cyan-400 bg-cyan-950/50 px-2 py-0.5 rounded whitespace-nowrap">
                  Oct 30, 2026
                </span>
              </div>

              <div className="pt-2 flex items-start justify-between gap-3 text-xs">
                <div>
                  <strong className="text-white">Monthly SLA & Security Audit</strong>
                  <p className="text-slate-400">Vendor uptime guarantee reconciliation (99.9% target).</p>
                </div>
                <span className="font-mono-code font-bold text-amber-400 bg-amber-950/50 px-2 py-0.5 rounded whitespace-nowrap">
                  Oct 05, 2026
                </span>
              </div>
            </div>
          </div>

          {/* Key Inconsistencies / Risks */}
          <div className="p-4 rounded-xl bg-yellow-950/20 border border-yellow-500/30 space-y-2">
            <span className="text-[10px] font-bold uppercase tracking-wider text-yellow-400 font-mono-code flex items-center gap-1.5">
              <AlertTriangle className="w-3.5 h-3.5" />
              <span>FLAGGED RISKS & CLAUSE CONFLICTS</span>
            </span>
            <p className="text-xs text-yellow-200/90 leading-relaxed">
              <strong>1. Conflicting Payment Schedules:</strong> Section 4.1 mandates Net 30 invoice settlements, while Exhibit B / Section 9.2 permits Net 45 payments. Recommend issuing a clarification addendum prior to next quarterly billing.
            </p>
            <p className="text-xs text-yellow-200/90 leading-relaxed">
              <strong>2. Uncapped Data Breach Indemnification:</strong> Client indemnification is uncapped for third-party intellectual property claims, while Vendor liability is capped at 12 months fees.
            </p>
          </div>
        </div>

        {/* Footer */}
        <div className="pt-3 border-t border-violet-950/80 flex items-center justify-between text-xs text-slate-400">
          <span className="text-[11px]">Prepared by ContractLens Agent · Ready for executive distribution</span>
          <div className="flex items-center gap-2">
            <button
              onClick={() => window.print()}
              className="px-3 py-1.5 rounded-lg bg-[#141A33] hover:bg-[#1E2548] text-xs font-bold text-slate-200 transition-colors flex items-center gap-1"
            >
              <Printer className="w-3.5 h-3.5" />
              <span>Print</span>
            </button>
            <button
              onClick={onClose}
              className="px-4 py-1.5 rounded-lg gradient-brand-cta text-xs font-bold uppercase tracking-wider text-white shadow-[0_0_10px_rgba(6,182,212,0.3)] transition-all"
            >
              Done
            </button>
          </div>
        </div>
      </div>
    </div>
  );
};
